using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BillisNet.Snark
{
    public static class SubredditSnark
    {
        public static List<string> subredditSnarkList = new List<string>()
        {
            { "Really? {0}? 'Just for the karma', right?" },
            { "The bots on {0} make fun of me." },
            { "To {0] or not to {0}, that is the question." },
            { "You ever use {0} to... you know? Just asking for a friend." },
            { "Ah, good old {0}..." },
            { "I can still remember the first time I saw {0}..." },
            { "Just so you know, {0} disturbs me." },
            { "May the {0} be with you. I guess." },
            { "There's no place like {0}. There's no place like {0}." },
            { "{0}. Easily my favorite subreddit." },
            { "Billions and billions of {0}s..." },
            { "Back in my day, we didn't have this fancy {0}." },
            { "Yes, yes, {0}. Got it. Anything else?" },
            { "I already thought you we a little weird, but now {0}?" },
            { "What could you possibly want from {0}?" },
            { "{0}ee-ki-yay, motherfucker!" },
            { "Give me liberty or give me {0}." },
            { "There's no place like {0}." },
            { "No, no, it's pronounced Franken-{0}!" },
            { "Here's looking at you, {0}" },
            { "{0}, my dear Watson." },
            { "Play it again, {0}." },
            { "We'll always have {0}" },
            { "{0}. James {0}." },
            { "Voulez-vous coucher avec {0}?" },
            { "You want {0}? You can't handle {0}!" },
            { "Let's get down to business - to defeat {0}!" },
            { "Houston, we have a {0}." },
            { "At my signal, unleash {0}." },
            { "Do we need to talk about why you're on {0} so much?" },
            { "{0} is a strange place to find porn..." },
            { "I am the Alpha and {0}." },
            { "Take this pill and see how far down {0} goes..." },
            { "I've got a bad feeling about {0}." },
            { "My mama always said life is like a box of {0}." },
            { "My mama always said {0} is like a box of chocolates." },
            { "{0} is as {0} does." },
            { "Two things are certain: {0}, and human stupidity." },
            { "So much {0}, so little time." },
            { "There's gotta be good wallpapers on {0}." },
            { "What do you even see in {0}?" },
            { "Wait, you're sending me to {0}?" },
            { "Be the {0} you wish to see in the world, I think." },
            { "Without {0}, life would be a mistake." },
            { "A specter haunts Europe; the specter of {0}." },
            { "{0}, the blood of angry men!" },
            { "All that is {0} does not glitter..." },
            { "I've not failed, just found 10,000 subreddits that aren't {0}." },
            { "One {0}, two {0}, red {0}, blue {0}." },
            { "Thou shalt not {0}." },
            { "Thou shalt {0}." },
            { "There's no greater agony than bearing {0} inside you, or something." },
            { "All you need is {0}." },
            { "To the well-organized mind, {0} is but the next great adventure." },
            { "Logic gets you from A-Z, but {0} gets you everywhere." },
            { "Go to heaven for the climate and {0} for the company." },
            { "I love subreddits; it's {0} I can't stand!" },
            { "{0}: A subreddit people praise but don't visit." },
            { "A day without {0} is wasted." },
            { "All that we see or seem is but a {0} inside a dream." },
            { "Call me {0}." },
            { "It was a bright, cold day in April, and all the clocks were striking {0}." },
            { "{0}, light of my life, fire of my loins." },
            { "In the midway of this, our mortal {0}..." },
            { "The sky above the {0} was the color of television..." },
            { "There was a boy called {0}, and he almost certainly deserved it." },
            { "It was a pleasure to burn {0}." },
            { "It was {0} at first sight." },
            { "Thou shalt not muzzle the ox when he treadeth out the {0}." },
            { "All you {0} are belong to us." },
            { "Those who cannot remember {0} are doomed to download its images again." },
            { "The only thing saving us from {0} is its inefficiency." },
            { "Better is {0} than a happy heart than {0} with vexation." },
            { "{0} is the best provision for old age." },
            { "The nation that destroys its {0} destroys itself." },
            { "My kingdom for a {0}!" },
            { "How happy are those whose {0} is already downloaded!" },
            { "{0} is the gate and key to good wallpapers." },
            { "I am become {0}, filler of hard drives." },
            { "The meek shall inherit {0}, but not its mineral rights." },
            { "There is only one good: knowledge, and one evil: {0}." },
            { "Shall the clay say to him that fashioneth it: 'Did you see this post on {0}?'" },
            { "He who commands {0} has command of all things." },
            { "He who destroys {0} destroys reason itself." },
            { "{0} and opprobrium are like two wheels of a Rascal scooter." },
            { "Give me your tired, your poor, your huddled masses yearning to see {0}." },
            { "Those who lose {0} are lost." },
            { "{0} is the essential concept and the first truth." },
            { "Numberless are the world's wonders, but none more wonderful than {0}." },
            { "{0} is the best subreddit." },
            { "Mr. Gorbachev, tear down this {0}!" },
            { "To achieve great things, two things are needed: {0}, and not enough time." },
            { "Quick, give me {0} and a cactus, there's no time to explain!" },
            { "Sex and {0} are closer to each other than either might prefer." },
            { "Do, or do not. There is no {0}." },
            { "There is no {0}." },
            { "There are no facts, only {0}." },
            { "Visiting {0} is the most unusual of all the perversions." },
            { "Never interrupt your enemy when he is making a mistake by surfing {0}." },
            { "If you are going through {0}, keep going." },
            { "Maybe {0} is another subreddit's hell." },
            { "{0} is where taste goes to die." },
            { "{0}. I had a wonderful time once, but not there." },
            { "Once you eliminate the impossible, whatever remains must be {0}." },
            { "Basically, I no longer work for anything except to surf {0} another day." },
            { "To love {0} is the beginning of a lifelong romance." },
            { "Knowledge speaks, but {0} provides the lulz." },
            { "A witty saying proves nothing. Neither does {0}. - Voltaire." },
            { "Don't believe everything you read on {0}. - Abraham Lincoln" },
            { "Enjoy every sandwich. And every post on {0}." }
        };
    }
}
